openapi: 3.0.0
servers:
  - url: /1.0/
info:
  description: Universal Registrar
  version: "1.0.0"
  title: Universal Registrar
  contact:
    email: markus@danubetech.com
paths:
  /create:
    post:
      summary: Creates a DID.
      operationId: create
      parameters:
        - in: query
          required: true
          name: driverId
          schema:
            type: string
          description: An identifier for a driver that implements the requested DID method.
          example: driver-universalregistrar/driver-did-sov
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRequest'
      responses:
        '200':
          description: successfully createed!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateState'
        '400':
          description: invalid input!
        '500':
          description: error!
  /update:
    post:
      summary: Updates a DID.
      operationId: update
      parameters:
        - in: query
          required: true
          name: driverId
          schema:
            type: string
          description: An identifier for a driver that implements the requested DID method.
          example: driver-universalregistrar/driver-did-sov
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRequest'
      responses:
        '200':
          description: successfully updated!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateState'
        '400':
          description: invalid input!
        '500':
          description: error!
  /deactivate:
    post:
      summary: Deactivates a DID.
      operationId: deactivate
      parameters:
        - in: query
          required: true
          name: driverId
          schema:
            type: string
          description: An identifier for a driver that implements the requested DID method.
          example: driver-universalregistrar/driver-did-sov
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeactivateRequest'
      responses:
        '200':
          description: successfully deactivated!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeactivateState'
        '400':
          description: invalid input!
        '500':
          description: error!
components:
  schemas:
    CreateRequest:
      description: Request parameters for the create operation.
      type: object
      additionalProperties: false
      properties:
        jobId:
          type: string
          example: 6d85bcd0-2ea3-4288-ab00-15afadd8a156
        options:
          type: object
          example: {"chain": "testnet"}
        secret:
          type: object
          example: {"seed": "72WGp7NgFR1Oqdi8zlt7jQQ434XR0cNQ"}
        didDocument:
          type: object
    UpdateRequest:
      description: Request parameters for the update operation.
      type: object
      additionalProperties: false
      required:
        - identifier
      properties:
        jobId:
          type: string
          example: 6d85bcd0-2ea3-4288-ab00-15afadd8a156
        identifier:
          type: string
          example: "did:sov:WRfXPg8dantKVubE3HX8pw"
        options:
          type: object
        secret:
          type: object
        didDocument:
          type: object
    DeactivateRequest:
      description: Request parameters for the deactivate operation.
      type: object
      additionalProperties: false
      required:
        - identifier
      properties:
        jobId:
          type: string
          example: 6d85bcd0-2ea3-4288-ab00-15afadd8a156
        identifier:
          type: string
          example: "did:sov:WRfXPg8dantKVubE3HX8pw"
        options:
          type: object
        secret:
          type: object
    CreateState:
      description: The state after a create operation.
      type: object
      additionalProperties: false
      required:
        - didState
      properties:
        jobId:
          type: string
          example: 6d85bcd0-2ea3-4288-ab00-15afadd8a156
        didState:
          type: object
          additionalProperties: true
          properties:
            state:
              type: string
              example: "finished"
            identifier:
              type: string
              example: "did:sov:WRfXPg8dantKVubE3HX8pw"
            secret:
              type: object
              example: {
  "keys": [
    {
      "privateKeyJwk": {
        "kty": "OKP",
        "d": "NzJXR3A3TmdGUjFPcWRpOHpsdDdqUVE0MzRYUjBjTlE",
        "crv": "Ed25519",
        "x": "jpIKKU2b77lNXKTNW2NGvw1GUMjU6v_l_tLJAH5uYz0"
      },
      "publicKeyDIDURL": "did:sov:WRfXPg8dantKVubE3HX8pw#key-1"
    }
  ]
}
        registrarMetadata:
          type: object
        methodMetadata:
          type: object
    UpdateState:
      description: The state after an update operation.
      type: object
      additionalProperties: false
      required:
        - didState
      properties:
        jobId:
          type: string
          example: 6d85bcd0-2ea3-4288-ab00-15afadd8a156
        didState:
          type: object
          additionalProperties: true
          properties:
            state:
              type: string
            secret:
              type: object
        registrarMetadata:
          type: object
        methodMetadata:
          type: object
    DeactivateState:
      description: The state after a deactivate operation.
      type: object
      additionalProperties: false
      required:
        - didState
      properties:
        jobId:
          type: string
          example: 6d85bcd0-2ea3-4288-ab00-15afadd8a156
        didState:
          type: object
          additionalProperties: true
          properties:
            state:
              type: string
        registrarMetadata:
          type: object
        methodMetadata:
          type: object
