openapi: 3.0.3
servers:
  - url: http://localhost:3000
    description: Local environment
  - url: http://api.universal-registrar.com
    description: Universal Registar
info:
  description: Universal Registrar endpoints
  version: "1.0.0"
  title: Universal Registrar
  contact:
    email: markus@danubetech.com
paths:
  /universal-registrar/v1/methods/{did-method}:
    post:
      summary: Create a new DID entry
      operationId: post-universal-registrar-v1-methods-create
      parameters:
        - in: path
          required: true
          name: did-method
          schema:
            type: string
            format: did:{method-name}
          description: The requested DID method for the operation.
          example: btcr
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRequest'
      responses:
        '200':
          description: successfully createed!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateState'
        '302':
          description: Redirect
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                redirect:
                  description: Redirect URI
                  value:
                    errorMessage: "redirect_uri: www.abc.com"

        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                signatureMissing:
                  description: Action Required
                  
        '500':
          description: error!
  /create:
    post:
      summary: Creates a DID.
      operationId: create
      parameters:
        - in: query
          required: true
          name: method
          schema:
            type: string
          description: The requested DID method for the operation.
          example: btcr
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRequest'
      responses:
        '200':
          description: successfully createed!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateState'
        '400':
          description: invalid input!
        '500':
          description: error!
  /update:
    post:
      summary: Updates a DID.
      operationId: update
      parameters:
        - in: query
          required: true
          name: method
          schema:
            type: string
          description: The requested DID method for the operation.
          example: btcr
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRequest'
      responses:
        '200':
          description: successfully updated!
          content:
            application/json:
              schema:
                type: string
                # $ref: '#/components/schemas/UpdateState'
        '400':
          description: invalid input!
        '500':
          description: error!
  /deactivate:
    post:
      summary: Deactivates a DID.
      operationId: deactivate
      parameters:
        - in: query
          required: true
          name: method
          schema:
            type: string
          description: The requested DID method for the operation.
          example: btcr
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeactivateRequest'
      responses:
        '200':
          description: successfully deactivated!
          content:
            application/json:
              schema:
                type: string
                # $ref: '#/components/schemas/DeactivateState'
        '400':
          description: invalid input!
        '500':
          description: error!
  /properties:
    get:
      summary: Returns a map of properties of the resolver.
      operationId: properties
      responses:
        '200':
          description: Success.
          content:
            application/did+json:
              schema:
                type: object
                description: A map of properties.
  /methods:
    get:
      summary: Returns a list of supported DID methods.
      operationId: methods
      responses:
        '200':
          description: Success.
          content:
            application/did+json:
              schema:
                type: array
                items:
                  type: string
                description: The list of supported DID methods.
                example: ["btcr","sov","v1","key"]
components:
  schemas:
    Error:
      description: Request parameters for the create operation.
      type: object
      properties:
        errorCode:
          type: string
        errorMessage:
          type: string

    CreateRequest:
      description: Request parameters for the create operation.
      type: object
      additionalProperties: false
      required:
        - did
        - state
        - didDocument
      properties:
        did:
          description: DID we want to create/register
          type: string
          format: W3C-compliant decentralized identifier
          example: did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w
        state:
          description: Opaque value used to maintain state between the request and the callback.
          type: string
          format: uuidv4
          example: 6d85bcd0-2ea3-4288-ab00-15afadd8a156
        options:
          description: <description goes here>
          type: object
          example: {"chain": "testnet"}
        secret:
          description: NOT RECOMMENDED. <description goes here>
          type: object
          example: {"seed": "72WGp7NgFR1Oqdi8zlt7jQQ434XR0cNQ"}
        didDocument:
          description: W3C-compliant DID Document.
          type: object
        proof:
          description: Proof required to submit the transaction
          type: object
          example:
            {
              "id": "https://identity.foundation/EcdsaSecp256k1RecoverySignature2020#EcdsaSecp256k1RecoverySignature2020",
              "type": "SignatureSuite",
              "canonicalizationAlgorithm": "https://w3id.org/security#URDNA2015",
              "digestAlgorithm": "https://www.ietf.org/assignments/jwa-parameters#SHA256",
              "signatureAlgorithm": "https://tools.ietf.org/html/rfc4880#section-11.4"
            }
    UpdateRequest:
      description: Request parameters for the update operation.
      type: object
      additionalProperties: false
      required:
        - did
      properties:
        jobId:
          type: string
          example: 6d85bcd0-2ea3-4288-ab00-15afadd8a156
        did:
          type: string
          example: "did:sov:WRfXPg8dantKVubE3HX8pw"
        options:
          type: object
        secret:
          type: object
        didDocument:
          type: object
    DeactivateRequest:
      description: Request parameters for the deactivate operation.
      type: object
      additionalProperties: false
      required:
        - did
      properties:
        jobId:
          type: string
          example: 6d85bcd0-2ea3-4288-ab00-15afadd8a156
        did:
          type: string
          example: "did:sov:WRfXPg8dantKVubE3HX8pw"
        options:
          type: object
        secret:
          type: object
    CreateState:
      description: The state after a create operation.
      type: object
      additionalProperties: false
      required:
        - didState
      properties:
        jobId:
          type: string
          example: 6d85bcd0-2ea3-4288-ab00-15afadd8a156
        didState:
          type: object
          additionalProperties: true
          properties:
            state:
              type: string
              example: "finished"
            did:
              type: string
              example: "did:sov:WRfXPg8dantKVubE3HX8pw"
            secret:
              type: object