# Dockerfile for universalregistrar/uni-registrar-web

FROM universalregistrar/base-alpine
MAINTAINER Markus Sabadello <markus@danubetech.com>

# build uni-registrar-web

ADD . /opt/uni-registrar-java

RUN cd /opt/uni-registrar-java && mvn clean && \
    cd /opt/uni-registrar-java && mvn install -N -DskipTests && \
    cd /opt/uni-registrar-java/uni-registrar-core && mvn install -N -DskipTests && \
    cd /opt/uni-registrar-java/driver && mvn install -N -DskipTests && \
    cd /opt/uni-registrar-java/driver-http && mvn install -N -DskipTests && \
    cd /opt/uni-registrar-java/uni-registrar-local && mvn install -N -DskipTests && \
    cd /opt/uni-registrar-java/uni-registrar-web && mvn install -N -DskipTests

# done

EXPOSE 9080

RUN chmod a+rx /opt/uni-registrar-java/docker/run-uni-registrar-web.sh
CMD "/opt/uni-registrar-java/docker/run-uni-registrar-web.sh"
